apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: csgo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: csgo 
    spec:
      containers:
        - name: csgo
          image:  edenservers/docker-csgo
          ports:
            - containerPort: 27015
            - containerPort: 27015
              protocol: UDP
            - containerPort: 1234
          env:
            - name: GAME_TYPE
              value: '0'
            - name: GAME_MODE
              value: '0'
            - name: MAPGROUP
              value: mg_bomb
            - name: MAP
              value: de_dust2
            - name: USERNAME
              value: cool
            - name: PASSWORD
              value: asodj812k3mamkasd89 
            # - name: STARTUP_OPTIONS
            #   value: "sv_lan 1"
