apiVersion: v1
kind: Service
metadata:
  name: csgo 
spec:
  type: LoadBalancer
  selector:
    app: csgo 
  ports:
    - name: 'main'
      port: 27015
      targetPort: 27015
      protocol: TCP
    - name: 'secondary'
      port: 27015
      targetPort: 27015
      protocol: UDP
  type: NodePort
